apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: apv5hd6nh-nodejs
  janus-idp.io/tekton: apv5hd6nh-nodejs
  backstage.io/kubernetes-id: apv5hd6nh-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: apv5hd6nh-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
