apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: apv5hd6nh-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apv5hd6nh-nodejs 
  name: apv5hd6nh-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: apv5hd6nh-nodejs 
